export const QUERY_KEYS = {
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  EMPLOYEE_DELETE: "EMPLOYEE_DELETE",
  EMPLOYEE_LIST: "EMPLOYEE_LIST",
  EMPLOYEE_BY_ID: "EMPLOYEE_BY_ID",
};
